-- Revert Product Names and Dimensions to Original

UPDATE public.products SET name = 'Agaria', dimensions = '120x60 cm', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-100';
UPDATE public.products SET name = 'Alubel', dimensions = '30x30 cm Sheet', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-101';
UPDATE public.products SET name = 'Ambekke', dimensions = '120x60 cm', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-102';
UPDATE public.products SET name = 'Arabescato Fay', dimensions = '30x30 cm Sheet', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-103';
UPDATE public.products SET name = 'Arabescato', dimensions = '30x30 cm Sheet', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-104';
UPDATE public.products SET name = 'Aurora Fay', dimensions = '60x60 cm', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-105';
UPDATE public.products SET name = 'Aurora', dimensions = '60x60 cm', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-106';
UPDATE public.products SET name = 'Bastia', dimensions = '30x30 cm Sheet', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-107';
UPDATE public.products SET name = 'Cool Rooftop', dimensions = '80x80 cm', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-108';
UPDATE public.products SET name = 'Caramella Fay', dimensions = '60x60 cm', finish = 'Polished', application = 'Interior' WHERE sku = 'UN-FLO-109';
UPDATE public.products SET name = '2.2 Square', dimensions = '60x60 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-100';
UPDATE public.products SET name = '2X2 Square Mosaic', dimensions = '30x30 cm Sheet', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-101';
UPDATE public.products SET name = '2X4 Bevel Mosaic', dimensions = '30x30 cm Sheet', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-102';
UPDATE public.products SET name = '2X4 Flat Mosaic', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-103';
UPDATE public.products SET name = 'Arabesque', dimensions = '120x60 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-104';
UPDATE public.products SET name = 'Circular', dimensions = '60x60 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-105';
UPDATE public.products SET name = 'Diamondback', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-106';
UPDATE public.products SET name = 'Elongated Hexagon', dimensions = '60x60 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-107';
UPDATE public.products SET name = 'Fan', dimensions = '120x60 cm', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-108';
UPDATE public.products SET name = 'Geometric', dimensions = '30x30 cm Sheet', finish = 'Glossy', application = 'Interior' WHERE sku = 'UN-MOS-109';
UPDATE public.products SET name = 'Pool Kafhsqlobs 0108B52', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-100';
UPDATE public.products SET name = 'Pool Kafhsqlocr 0105A52', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-101';
UPDATE public.products SET name = 'Pool Kafhsqlocr 0105C52', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-102';
UPDATE public.products SET name = 'Pool Kafhsqloka 0109B52', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-103';
UPDATE public.products SET name = 'Pool Kafhsqloka 0109C52', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-104';
UPDATE public.products SET name = 'Pool Kafhsqlooe 0107A52', dimensions = '30x30 cm Sheet', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-105';
UPDATE public.products SET name = 'Pool Kafhsqlowa 0106A52', dimensions = '80x80 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-106';
UPDATE public.products SET name = 'Pool Kafhsqlowa 0106B52', dimensions = '60x60 cm', finish = 'Glossy', application = 'Interior/Exterior' WHERE sku = 'UN-POO-107';
UPDATE public.products SET name = 'Agate', dimensions = '120x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-100';
UPDATE public.products SET name = 'Autumn Gloss', dimensions = '60x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-101';
UPDATE public.products SET name = 'Cement Wash', dimensions = '30x30 cm Sheet', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-102';
UPDATE public.products SET name = 'Colonize', dimensions = '120x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-103';
UPDATE public.products SET name = 'Ensign', dimensions = '60x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-104';
UPDATE public.products SET name = 'Hexagon', dimensions = '60x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-105';
UPDATE public.products SET name = 'Ketayama', dimensions = '30x30 cm Sheet', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-106';
UPDATE public.products SET name = 'Lasquire', dimensions = '120x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-107';
UPDATE public.products SET name = 'Luminara', dimensions = '120x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-108';
UPDATE public.products SET name = 'Lushfade', dimensions = '60x60 cm', finish = 'Matte', application = 'Interior' WHERE sku = 'UN-WAL-109';
